CREATE TABLE FINANCIAL_REPORTS
(
BASE_DATE VARCHAR(40),
MARKET VARCHAR(40),
STOCKK_CODE VARCHAR(40),
COMPANY_NAME VARCHAR(40),
ACCOUNTING_STANDARD VARCHAR(40),
UNIT VARCHAR(40),
TOTAL_ASSETS VARCHAR(40),
CURRENT_ASSETS VARCHAR(40),
NON_CURRENT_ASSETS VARCHAR(40),
OTHER_FINANCIAL_INSTITUTIONS_ASSETS VARCHAR(40),
TOTAL_LIABILITIES VARCHAR(40),
CURRENT_LIABILITIES VARCHAR(40),
NON_CURRENT_LIABILITIES VARCHAR(40),
OTHER_FINANCIAL_INSTITUTIONS_LIABILITIES VARCHAR(40),
TOTAL_STOCKHOLDER_EQUITY VARCHAR(40),
OWNERS_OF_PARENT_EQUITY VARCHAR(40),
NON_CONTROLLING_INTERESTS_EQUITY VARCHAR(40),
NET_SALES VARCHAR(40),
COST_OF_SALES VARCHAR(40),
GROSS_PROFIT VARCHAR(40),
OTHER_OPERATING_INCOME VARCHAR(40),
DISTRIBUTION_COSTS_ADMINISTRATIVE_EXPENSES VARCHAR(40),
OTHER_OPERATING_EXPENSES VARCHAR(40),
OPERATING_INCOME_REPORTED VARCHAR(40),
OPERATING_INCOME_CAL VARCHAR(40),
OTHER_NON_OPERATING_INCOME VARCHAR(40),
OTHER_NON_OPERATING_EXPENSES VARCHAR(40),
FINANCIAL_INCOME VARCHAR(40),
FINANCIAL_COSTS VARCHAR(40),
GAINS_IN_SUBSIDIARIES_JOINT_VENTURES_ASSOCIATES VARCHAR(40),
INCOME_BEFORE_INCOME_TAXES_EXPENSES VARCHAR(40),
INCOME_TAXES_EXPENSES VARCHAR(40),
NET_PROFIT_FROM_SUBSIDIES_BEFORE_ACQUISITION VARCHAR(40),
NET_INCOME_FROM_DISPOSED_SUBSIDIES VARCHAR(40),
ONGOING_OPERATING_INCOME VARCHAR(40),
DISCONTINUED_OPERATING_INCOME VARCHAR(40),
PROFIT VARCHAR(40),
OTHER_COMPREHENSIVE_INCOME VARCHAR(40),
TOTAL_COMPREHENSIVE_INCOME VARCHAR(40),
NET_INCOME_OWNERS_OF_PARENT_EQUITY VARCHAR(40),
NET_INCOME_NON_CONTROLLING_INTERESTS_EQUITY VARCHAR(40),
TOTAL_INCOME_OWNERS_OF_PARENT_EQUITY VARCHAR(40),
TOTAL_INCOME_NON_CONTROLLING_INTERESTS_EQUITY VARCHAR(40),
CASH_FLOWS_FROM_OPERATINGS VARCHAR(40),
CASH_FLOWS_FROM_INVESTING VARCHAR(40),
CASH_FLOWS_FROM_FINANCING VARCHAR(40),
PRIMARY KEY (STOCKK_CODE,BASE_DATE)
);


CREATE TABLE SS_VALUE
(
BASE_DATE VARCHAR(40),
STOCK_CODE VARCHAR(40),
COMPANY_NAME VARCHAR(40),
PBR VARCHAR(40),
PER VARCHAR(40),
PCR VARCHAR(40),
PSR VARCHAR(40),
PBR_RANK VARCHAR(40),
PER_RANK VARCHAR(40),
PCR_RANK VARCHAR(40),
PSR_RANK VARCHAR(40),
SUM_RANK VARCHAR(40),
SS_PRICE VARCHAR(40),
GROWTH_SCORE VARCHAR(40)
);

alter table [테이블명] add [컬럼명] [타입] [옵션];


